# Generated by Django 5.1.3 on 2025-05-16 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_maplocation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MapLocation',
        ),
    ]
